#!/bin/bash
#
# Remote Claude - Dedicated Credentials Setup
#
# Sets up dedicated git and GCP credentials for Claude YOLO sessions.
# Supports both GitHub.com and GitHub Enterprise.
#
# Usage:
#   ./setup/credentials-setup.sh              # Interactive setup
#   ./setup/credentials-setup.sh --git-only   # Only setup git credentials
#   ./setup/credentials-setup.sh --gcp-only   # Only setup GCP credentials
#   ./setup/credentials-setup.sh --status     # Show current configuration

set -e

# Configuration
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/remote-claude"
CREDS_DIR="$CONFIG_DIR/credentials"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
header() { echo -e "\n${BLUE}=== $1 ===${NC}\n"; }

# Create directory structure
init_directories() {
    mkdir -p "$CREDS_DIR/git/.ssh"
    mkdir -p "$CREDS_DIR/gcp"
    chmod 700 "$CREDS_DIR/git/.ssh"
}

# Setup Git credentials
setup_git_credentials() {
    header "Git Credentials Setup"

    echo "This will create a dedicated git identity and SSH key for Claude sessions."
    echo "You should use a separate GitHub account (bot account) for Claude."
    echo ""

    # Ask about GitHub type
    echo "What type of GitHub do you use?"
    echo "  1. GitHub.com only"
    echo "  2. GitHub Enterprise only"
    echo "  3. Both GitHub.com and GitHub Enterprise"
    echo ""
    read -p "Select [1]: " github_type
    github_type=${github_type:-1}

    local gh_enterprise_host=""
    if [[ "$github_type" == "2" || "$github_type" == "3" ]]; then
        read -p "GitHub Enterprise hostname (e.g., github.mycompany.com): " gh_enterprise_host
        if [[ -z "$gh_enterprise_host" ]]; then
            error "Enterprise hostname is required"
            return 1
        fi
    fi

    # Get bot account details
    echo ""
    read -p "Bot account username (e.g., yourname-claude-bot): " bot_username
    read -p "Bot account email: " bot_email

    if [[ -z "$bot_username" || -z "$bot_email" ]]; then
        error "Username and email are required"
        return 1
    fi

    # Check for existing key
    local ssh_key="$CREDS_DIR/git/.ssh/id_ed25519"
    if [[ -f "$ssh_key" ]]; then
        warn "SSH key already exists at $ssh_key"
        read -p "Overwrite? [y/N]: " overwrite
        if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
            info "Keeping existing SSH key"
        else
            rm -f "$ssh_key" "$ssh_key.pub"
        fi
    fi

    # Generate SSH key if needed
    if [[ ! -f "$ssh_key" ]]; then
        info "Generating SSH key..."
        ssh-keygen -t ed25519 -f "$ssh_key" -N "" -C "$bot_email"
        chmod 600 "$ssh_key"
        chmod 644 "$ssh_key.pub"
    fi

    # Create SSH config
    info "Creating SSH config..."
    local ssh_config="$CREDS_DIR/git/.ssh/config"
    cat > "$ssh_config" << EOF
# SSH config for Remote Claude bot account
# Generated by credentials-setup.sh

EOF

    if [[ -n "$gh_enterprise_host" ]]; then
        cat >> "$ssh_config" << EOF
# GitHub Enterprise
Host $gh_enterprise_host
    HostName $gh_enterprise_host
    User git
    IdentityFile $ssh_key
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new

EOF
    fi

    if [[ "$github_type" == "1" || "$github_type" == "3" ]]; then
        cat >> "$ssh_config" << EOF
# GitHub.com
Host github.com
    HostName github.com
    User git
    IdentityFile $ssh_key
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
EOF
    fi

    chmod 600 "$ssh_config"

    # Create git config
    info "Creating git config..."
    local git_config="$CREDS_DIR/git/.gitconfig"
    cat > "$git_config" << EOF
[user]
    name = $bot_username
    email = $bot_email

[push]
    default = simple
    autoSetupRemote = true

[pull]
    rebase = false

[init]
    defaultBranch = main

# Safety: prevent force push
[receive]
    denyNonFastForwards = true
EOF

    # Add enterprise URL rewrite if needed
    if [[ -n "$gh_enterprise_host" ]]; then
        cat >> "$git_config" << EOF

# GitHub Enterprise URL rewrite
[url "git@$gh_enterprise_host:"]
    insteadOf = https://$gh_enterprise_host/
EOF
    fi

    # Display public key
    echo ""
    info "SSH public key (add this to your bot account's GitHub settings):"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    cat "$ssh_key.pub"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Instructions
    echo "Next steps:"
    echo "  1. Create a new GitHub account for Claude (if you haven't already)"
    echo "  2. Go to GitHub Settings > SSH and GPG keys > New SSH key"
    echo "  3. Paste the public key shown above"
    if [[ -n "$gh_enterprise_host" ]]; then
        echo "  4. For Enterprise SSO: Click 'Configure SSO' and authorize the key"
    fi
    echo "  5. Add the bot account as a collaborator to repos Claude needs access to"
    echo ""

    read -p "Press Enter when you've completed these steps..."

    # Test connection
    echo ""
    info "Testing SSH connection..."
    if [[ "$github_type" == "1" || "$github_type" == "3" ]]; then
        echo "Testing github.com..."
        ssh -T -F "$ssh_config" -i "$ssh_key" git@github.com 2>&1 || true
    fi
    if [[ -n "$gh_enterprise_host" ]]; then
        echo "Testing $gh_enterprise_host..."
        ssh -T -F "$ssh_config" -i "$ssh_key" "git@$gh_enterprise_host" 2>&1 || true
    fi

    info "Git credentials setup complete!"
    echo "  Config: $git_config"
    echo "  SSH: $CREDS_DIR/git/.ssh/"
}

# Setup GCP credentials
setup_gcp_credentials() {
    header "GCP Credentials Setup"

    echo "This will create a limited service account for Claude sessions."
    echo "The service account will have restricted permissions (no admin/delete)."
    echo ""

    # Check if gcloud is available
    if ! command -v gcloud &> /dev/null; then
        warn "gcloud CLI not found"
        echo ""
        echo "Options:"
        echo "  1. Provide an existing service account key file"
        echo "  2. Skip GCP setup"
        echo ""
        read -p "Select [2]: " gcp_option
        gcp_option=${gcp_option:-2}

        if [[ "$gcp_option" == "1" ]]; then
            read -p "Path to service account key JSON: " key_path
            if [[ -f "$key_path" ]]; then
                cp "$key_path" "$CREDS_DIR/gcp/claude-sa-key.json"
                chmod 600 "$CREDS_DIR/gcp/claude-sa-key.json"
                info "Service account key copied to $CREDS_DIR/gcp/claude-sa-key.json"
            else
                error "File not found: $key_path"
                return 1
            fi
        else
            info "Skipping GCP setup"
            return 0
        fi
    else
        # Use gcloud to create service account
        echo "Available options:"
        echo "  1. Create new service account (recommended)"
        echo "  2. Use existing service account key"
        echo "  3. Skip GCP setup"
        echo ""
        read -p "Select [1]: " gcp_option
        gcp_option=${gcp_option:-1}

        case "$gcp_option" in
            1)
                # Get project ID
                local current_project=$(gcloud config get-value project 2>/dev/null)
                read -p "GCP Project ID [$current_project]: " project_id
                project_id=${project_id:-$current_project}

                if [[ -z "$project_id" ]]; then
                    error "Project ID is required"
                    return 1
                fi

                local sa_name="claude-agent"
                local sa_email="${sa_name}@${project_id}.iam.gserviceaccount.com"

                # Check if service account exists
                if gcloud iam service-accounts describe "$sa_email" --project="$project_id" &>/dev/null; then
                    warn "Service account $sa_email already exists"
                    read -p "Use existing account? [Y/n]: " use_existing
                    if [[ "$use_existing" == "n" || "$use_existing" == "N" ]]; then
                        return 1
                    fi
                else
                    info "Creating service account..."
                    gcloud iam service-accounts create "$sa_name" \
                        --project="$project_id" \
                        --display-name="Claude YOLO Agent" \
                        --description="Limited service account for Remote Claude sessions"
                fi

                # Grant roles
                info "Granting roles..."
                local roles=(
                    "roles/viewer"
                    "roles/run.developer"
                    "roles/storage.objectAdmin"
                    "roles/logging.viewer"
                )

                for role in "${roles[@]}"; do
                    echo "  Adding $role..."
                    gcloud projects add-iam-policy-binding "$project_id" \
                        --member="serviceAccount:$sa_email" \
                        --role="$role" \
                        --quiet &>/dev/null || true
                done

                # Create key
                info "Creating service account key..."
                local key_file="$CREDS_DIR/gcp/claude-sa-key.json"
                gcloud iam service-accounts keys create "$key_file" \
                    --iam-account="$sa_email" \
                    --project="$project_id"
                chmod 600 "$key_file"

                info "GCP credentials setup complete!"
                echo "  Service Account: $sa_email"
                echo "  Key File: $key_file"
                echo ""
                echo "Roles granted:"
                for role in "${roles[@]}"; do
                    echo "  - $role"
                done
                ;;
            2)
                read -p "Path to service account key JSON: " key_path
                if [[ -f "$key_path" ]]; then
                    cp "$key_path" "$CREDS_DIR/gcp/claude-sa-key.json"
                    chmod 600 "$CREDS_DIR/gcp/claude-sa-key.json"
                    info "Service account key copied to $CREDS_DIR/gcp/claude-sa-key.json"
                else
                    error "File not found: $key_path"
                    return 1
                fi
                ;;
            *)
                info "Skipping GCP setup"
                return 0
                ;;
        esac
    fi
}

# Update config.yaml with credential paths
update_config() {
    header "Updating Configuration"

    # Check if config file exists
    if [[ ! -f "$CONFIG_FILE" ]]; then
        info "Creating new config file..."
        mkdir -p "$(dirname "$CONFIG_FILE")"
        cat > "$CONFIG_FILE" << EOF
# Remote Claude Configuration
# Generated by credentials-setup.sh

docker:
  image: remote-claude:latest

credentials:
EOF
    fi

    # Check which credentials exist
    local git_config="$CREDS_DIR/git/.gitconfig"
    local ssh_dir="$CREDS_DIR/git/.ssh"
    local gcp_key="$CREDS_DIR/gcp/claude-sa-key.json"

    # Use Python to update YAML (safer than sed)
    python3 << EOF
import yaml
from pathlib import Path

config_file = Path("$CONFIG_FILE")
config = yaml.safe_load(config_file.read_text()) if config_file.exists() else {}

if "credentials" not in config:
    config["credentials"] = {}

# Update credential paths if they exist
if Path("$git_config").exists():
    config["credentials"]["claude_git"] = "$git_config"
    print("  Added claude_git: $git_config")

if Path("$ssh_dir").exists():
    config["credentials"]["claude_ssh"] = "$ssh_dir"
    print("  Added claude_ssh: $ssh_dir")

if Path("$gcp_key").exists():
    config["credentials"]["claude_gcp"] = "$gcp_key"
    print("  Added claude_gcp: $gcp_key")

config_file.write_text(yaml.dump(config, default_flow_style=False, sort_keys=False))
EOF

    info "Configuration updated: $CONFIG_FILE"
}

# Show current status
show_status() {
    header "Current Credential Configuration"

    echo "Config Directory: $CONFIG_DIR"
    echo "Credentials Directory: $CREDS_DIR"
    echo ""

    # Git credentials
    echo "Git Credentials:"
    if [[ -f "$CREDS_DIR/git/.gitconfig" ]]; then
        echo "  Config: $CREDS_DIR/git/.gitconfig"
        local bot_name=$(grep "name = " "$CREDS_DIR/git/.gitconfig" | head -1 | sed 's/.*name = //')
        local bot_email=$(grep "email = " "$CREDS_DIR/git/.gitconfig" | head -1 | sed 's/.*email = //')
        echo "    User: $bot_name <$bot_email>"
    else
        echo "  Config: NOT CONFIGURED"
    fi

    if [[ -f "$CREDS_DIR/git/.ssh/id_ed25519" ]]; then
        echo "  SSH Key: $CREDS_DIR/git/.ssh/id_ed25519"
    else
        echo "  SSH Key: NOT CONFIGURED"
    fi
    echo ""

    # GCP credentials
    echo "GCP Credentials:"
    if [[ -f "$CREDS_DIR/gcp/claude-sa-key.json" ]]; then
        echo "  Key: $CREDS_DIR/gcp/claude-sa-key.json"
        local sa_email=$(python3 -c "import json; print(json.load(open('$CREDS_DIR/gcp/claude-sa-key.json'))['client_email'])" 2>/dev/null || echo "unknown")
        echo "    Service Account: $sa_email"
    else
        echo "  Key: NOT CONFIGURED"
    fi
    echo ""

    # Config file
    echo "Config File: $CONFIG_FILE"
    if [[ -f "$CONFIG_FILE" ]]; then
        echo "  Status: EXISTS"
        if grep -q "claude_git\|claude_ssh\|claude_gcp" "$CONFIG_FILE" 2>/dev/null; then
            echo "  Dedicated credentials: ENABLED"
        else
            echo "  Dedicated credentials: NOT CONFIGURED"
        fi
    else
        echo "  Status: NOT FOUND"
    fi
}

# Main
main() {
    echo "Remote Claude - Dedicated Credentials Setup"
    echo "==========================================="

    case "${1:-}" in
        --git-only)
            init_directories
            setup_git_credentials
            update_config
            ;;
        --gcp-only)
            init_directories
            setup_gcp_credentials
            update_config
            ;;
        --status)
            show_status
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --git-only   Only setup git credentials"
            echo "  --gcp-only   Only setup GCP credentials"
            echo "  --status     Show current configuration"
            echo "  --help       Show this help message"
            echo ""
            echo "Without options, runs interactive setup for both git and GCP."
            ;;
        *)
            init_directories

            echo ""
            echo "This wizard will set up dedicated credentials for Claude sessions."
            echo "Claude will use these instead of your personal credentials."
            echo ""

            read -p "Setup git credentials (for GitHub)? [Y/n]: " do_git
            if [[ "$do_git" != "n" && "$do_git" != "N" ]]; then
                setup_git_credentials
            fi

            read -p "Setup GCP credentials? [Y/n]: " do_gcp
            if [[ "$do_gcp" != "n" && "$do_gcp" != "N" ]]; then
                setup_gcp_credentials
            fi

            update_config

            header "Setup Complete"
            echo "Dedicated credentials have been configured."
            echo "New Claude sessions will use these credentials automatically."
            echo ""
            echo "To verify, run: $0 --status"
            ;;
    esac
}

main "$@"
